# Generated by Django 5.2.7 on 2025-10-18 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_accept_marketing_user_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagem')),
                ('category', models.CharField(choices=[('work', 'Trabalho Realizado'), ('before_after', 'Antes e Depois'), ('vehicle', 'Veículo'), ('detail', 'Detalhe')], default='work', max_length=20, verbose_name='Categoria')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Texto alternativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
                'db_table': 'core_gallery_image',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Imagem')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Texto alternativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Imagem Hero',
                'verbose_name_plural': 'Imagens Hero',
                'db_table': 'core_hero_image',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Imagem')),
                ('service_type', models.CharField(choices=[('washing', 'Lavagem'), ('detailing', 'Detalhamento'), ('polishing', 'Polimento'), ('ceramic', 'Proteção Cerâmica'), ('wheel_cleaning', 'Limpeza de Rodas'), ('interior', 'Limpeza Interna'), ('waxing', 'Enceramento'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Serviço')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Texto alternativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Imagem de Serviço',
                'verbose_name_plural': 'Imagens de Serviços',
                'db_table': 'core_service_image',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
