# Generated by Django 5.2.7 on 2025-10-18 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_galleryimage_heroimage_serviceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('background_image', models.ImageField(upload_to='hero/backgrounds/', verbose_name='Imagem de Background')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Texto alternativo')),
                ('transparency', models.FloatField(choices=[(0.1, '10% - Muito sutil'), (0.2, '20% - Sutil'), (0.3, '30% - Leve'), (0.4, '40% - Moderado'), (0.5, '50% - Meio termo'), (0.6, '60% - Visível'), (0.7, '70% - Forte'), (0.8, '80% - Muito forte'), (0.9, '90% - Quase opaco'), (1.0, '100% - Totalmente opaco')], default=0.3, help_text='Controla a opacidade da imagem de background', verbose_name='Transparência')),
                ('blur_effect', models.BooleanField(default=False, help_text='Aplica desfoque na imagem', verbose_name='Efeito Blur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Hero Background',
                'verbose_name_plural': 'Hero Backgrounds',
                'db_table': 'core_hero_background',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
