# Generated by Django 5.2.7 on 2025-10-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_herobackground'),
    ]

    operations = [
    ]
