# Generated by Django 5.2.6 on 2025-10-18 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20251018_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('washing', 'Lavagem Detalhada'), ('polishing', 'Polimento Profissional'), ('ceramic', 'Proteção Cerâmica'), ('interior', 'Higienização Interna'), ('headlight', 'Revitalização de Faróis'), ('leather', 'Hidratação de Couro'), ('wheel_cleaning', 'Limpeza de Rodas'), ('detailing', 'Detalhamento'), ('waxing', 'Enceramento'), ('other', 'Outro')], max_length=20, unique=True, verbose_name='Tipo de Serviço')),
                ('title', models.CharField(max_length=100, verbose_name='Título do Serviço')),
                ('description', models.TextField(verbose_name='Descrição do Serviço')),
                ('price_from', models.DecimalField(decimal_places=2, help_text='Preço base do serviço', max_digits=8, verbose_name='Preço A Partir De (R$)')),
                ('custom_icon', models.ImageField(blank=True, help_text='Imagem pequena (64x64px recomendado) para substituir o ícone padrão', null=True, upload_to='service_icons/', verbose_name='Ícone Personalizado')),
                ('fallback_icon', models.CharField(default='settings', help_text='Nome do ícone Lucide para usar se não houver imagem personalizada', max_length=50, verbose_name='Ícone Fallback')),
                ('badge', models.CharField(choices=[('none', 'Nenhum'), ('popular', 'Mais Popular'), ('premium', 'Premium'), ('new', 'Novo'), ('promocao', 'Promoção')], default='none', max_length=20, verbose_name='Badge do Card')),
                ('card_color', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('purple', 'Roxo'), ('orange', 'Laranja'), ('red', 'Vermelho'), ('teal', 'Verde-água')], default='blue', max_length=20, verbose_name='Cor do Card')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ícone de Serviço',
                'verbose_name_plural': 'Ícones de Serviços',
                'db_table': 'core_service_icon',
                'ordering': ['order', 'service_type'],
            },
        ),
    ]
