# Generated by Django 5.2.6 on 2025-10-17 20:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='applies_to_motorcycle',
            field=models.BooleanField(default=False, verbose_name='Aplica-se a Motocicleta'),
        ),
        migrations.AlterField(
            model_name='service',
            name='applies_to_pickup',
            field=models.BooleanField(default=True, verbose_name='Aplica-se a Pickup/Van'),
        ),
        migrations.AlterField(
            model_name='service',
            name='applies_to_sedan',
            field=models.BooleanField(default=True, verbose_name='Aplica-se a Sedan/Hatch'),
        ),
        migrations.AlterField(
            model_name='service',
            name='applies_to_suv',
            field=models.BooleanField(default=True, verbose_name='Aplica-se a SUV'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criada em'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='services/images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Serviço'),
        ),
    ]
