# Generated by Django 5.2.6 on 2025-10-24 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_applies_to_motorcycle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['categoria', 'nome'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria de Serviço', 'verbose_name_plural': 'Categorias de Serviços'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='applies_to_motorcycle',
            new_name='aplica_moto',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='applies_to_pickup',
            new_name='aplica_pickup',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='applies_to_sedan',
            new_name='aplica_sedan',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='applies_to_suv',
            new_name='aplica_suv',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='is_active',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='updated_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='duration_minutes',
            new_name='duracao_minutos',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='is_active',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='serviceimage',
            old_name='created_at',
            new_name='criada_em',
        ),
        migrations.RenameField(
            model_name='serviceimage',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='serviceimage',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='serviceimage',
            old_name='is_primary',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='serviceimage',
            old_name='service',
            new_name='servico',
        ),
    ]
