# Generated by Django 5.2.6 on 2025-10-17 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('services', '0002_alter_service_applies_to_motorcycle_and_more'),
        ('vehicles', '0002_alter_vehicle_created_at_alter_vehicle_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluído em'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vehicles.vehicle', verbose_name='Veículo'),
        ),
        migrations.AlterField(
            model_name='appointmentreview',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='appointments.appointment', verbose_name='Agendamento'),
        ),
        migrations.AlterField(
            model_name='appointmentreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criada em'),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='appointments.appointment', verbose_name='Agendamento'),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='Dia da Semana'),
        ),
    ]
