# Generated by Django 5.2.6 on 2025-10-24 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_completed_at_and_more'),
        ('services', '0003_alter_service_options_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-data_agendamento', '-horario_agendamento'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['data'], 'verbose_name': 'Feriado', 'verbose_name_plural': 'Feriados'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['dia_semana'], 'verbose_name': 'Horário de Funcionamento', 'verbose_name_plural': 'Horários de Funcionamento'},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='updated_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='completed_at',
            new_name='concluido_em',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='data_agendamento',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='horario_agendamento',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='started_at',
            new_name='iniciado_em',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='notes',
            new_name='observacoes',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='queue_position',
            new_name='posicao_fila',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='total_price',
            new_name='preco_total',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='status',
            new_name='situacao',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='vehicle',
            new_name='veiculo',
        ),
        migrations.RenameField(
            model_name='appointmentreview',
            old_name='appointment',
            new_name='agendamento',
        ),
        migrations.RenameField(
            model_name='appointmentreview',
            old_name='rating',
            new_name='avaliacao',
        ),
        migrations.RenameField(
            model_name='appointmentreview',
            old_name='comment',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='appointmentreview',
            old_name='created_at',
            new_name='criada_em',
        ),
        migrations.RenameField(
            model_name='appointmentservice',
            old_name='appointment',
            new_name='agendamento',
        ),
        migrations.RenameField(
            model_name='appointmentservice',
            old_name='is_completed',
            new_name='concluido',
        ),
        migrations.RenameField(
            model_name='appointmentservice',
            old_name='price',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='appointmentservice',
            old_name='service',
            new_name='servico',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='is_recurring',
            new_name='recorrente',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='is_open',
            new_name='aberto',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='weekday',
            new_name='dia_semana',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='end_time',
            new_name='horario_fim',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='start_time',
            new_name='horario_inicio',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('data_agendamento', 'horario_agendamento')},
        ),
        migrations.AlterUniqueTogether(
            name='appointmentservice',
            unique_together={('agendamento', 'servico')},
        ),
    ]
