# Generated by Django 5.2.6 on 2025-09-10 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('color', models.CharField(max_length=30, verbose_name='Cor')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('category', models.CharField(choices=[('sedan', 'Sedan'), ('hatch', 'Hatchback'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('van', 'Van'), ('motorcycle', 'Motocicleta'), ('other', 'Outro')], default='sedan', max_length=20, verbose_name='Categoria')),
                ('mileage', models.IntegerField(blank=True, null=True, verbose_name='Quilometragem')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'vehicles_vehicle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/images/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Imagem do Veículo',
                'verbose_name_plural': 'Imagens dos Veículos',
                'db_table': 'vehicles_vehicleimage',
            },
        ),
    ]
