# Generated by Django 5.2.6 on 2025-10-24 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_created_at_alter_vehicle_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='year',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='is_active',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='updated_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='color',
            new_name='cor',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='make',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='model',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='plate',
            new_name='placa',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='mileage',
            new_name='quilometragem',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='created_at',
            new_name='criada_em',
        ),
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='is_primary',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='vehicle',
            new_name='veiculo',
        ),
    ]
